### ISSUE TITLE
ClickUp API URL not passed through - cURL 3 Error

### ISSUE THREAD

**Issue by crazycoz** [spinen/laravel-clickup#13]
Hello! It's very possible I just set things up incorrectly. But, using Laravel 7, and following your instructions exactly, it appears that the CLICKUP_URL environment variable, as well as the default value found in config/clickup.php, were not being passed along through the Client, and thus, Guzzle would attempt to submit a cURL request to the raw API endpoint instead of the full URL. Example: It would submit a request to "/team" instead of "https://api.clickup.com/api/v2/team".

To get around this, I had to manually go into the `vendor/spinen/laravel-clickup/src/Api/Client.php` file, and on line 252 (the `uri` function), I replaced the default `NULL` value of the `$url` variable with `"https://api.clickup.com/api/v2"`.

Example: Replace `$url = NULL` with `$url = "https://api.clickup.com/api/v2"`.

After doing this, I could reach ClickUp API resources as expected. Prior to this, Laravel would throw a cURL type 3 error.

Am I doing things wrong? Or is this a real bug?

Otherwise, awesome job you guys, thanks for the awesome package!

**Comment by ssfinney** [comment]
Hey @crazycoz! Thanks for letting us know. I'll look into reproducing this. Could you let me know what Guzzle version you are using in your Laravel app? It should be 6.4 or 6.5 I think. If you don't know, tell me your exact Laravel version.

**Comment by ssfinney** [comment]
@crazycoz And by the way, we just pushed a bugfix up as version `1.2.4` so make sure to pick up the new version. Maybe it'll help!
