### ISSUE TITLE
When I use OAuth with artisan tinker, accessing the user's clickup_token gives me DecryptException

### ISSUE THREAD

**Issue by ssfinney** [spinen/laravel-clickup#18]
Steps to reproduce:

- Fresh Laravel database
- Set ClickUp configs properly in .env
- Register new user
- Open `php artisan tinker`
- Create new client: `$clickup = app(Spinen\ClickUp\Api\Client::class)`
- Generate SSO URL: `$clickup->oauthUri(route('clickup.sso.redirect_url', 1))`
- Follow redirect and authorize access to my ClickUp workspace
- Come back to tinker and get the correct user: `$user = App\User::find(1)`
- Access clickup_token: `$user->clickup_token`
- Error: `Illuminate/Contracts/Encryption/DecryptException with message 'The MAC is invalid.'`

**Comment by jimmypuckett** [comment]
I think that this is linked to #29

**Comment by jimmypuckett** [comment]
I am going to address this in #30 by swapping to the `Crypt` facade.
