### ISSUE TITLE
Field value update not working

### ISSUE THREAD

**Issue by vaslv** [spinen/laravel-clickup#25]
I am trying to update the value of a custom field in a task. It seems that the request path does not contain the identifier of the task in which you need to update the value of the custom field

**Comment by ssfinney** [comment]
Yeah, custom field setting is tricky. From the [ClickUp API](https://clickup.com/api), get the ID of the custom field first with this endpoint: `list/list_id/field`

Then, you can update the custom field on a specific task with: `task/task_id/field/field_id/?custom_task_ids=&team_id=`

**Comment by ssfinney** [comment]
@vaslv Let me know what other questions you have, otherwise I'll close this
