### ISSUE TITLE
Documentation - Subtasks and closed tasks

### ISSUE THREAD

**Issue by JeremyBellaiche** [spinen/laravel-clickup#3]
Hello guys,

To start, I really like your work. It helps me a lot in my research on the Clickup API. 

I have few questions : 

- Do you have an idea about how to add the parameters on the different requests ? 

For example, on this request : https://jsapi.apiary.io/apis/clickup20/reference/0/tasks/get-tasks.html

There is a lot of different parameters I must use and I want to understand if your package allow me to pass these arguments : 

- archived
- substasks
- include_closed

Thanks a lot !

Jeremy

**Comment by jimmypuckett** [comment]
Check the `Advanced filtering using "where"` section of the README...

https://github.com/spinen/laravel-clickup#advanced-filtering-using-where

I think that is what you are looking for.  If not, then please let us know.

**Comment by robertkent** [comment]
Thanks that's just what I was looking for as well:

auth()->user()->clickup()->teams->first()->tasks()->where('include_closed', true)->get()
